"""add fork_url and pr_number to workspaces

Revision ID: aa5d6c565188
Revises: 7fd693f7acc0
Create Date: 2026-06-13 15:55:59.512303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5d6c565188'
down_revision: Union[str, Sequence[str], None] = '7fd693f7acc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('fork_url', sa.String(length=500), nullable=True))
    op.add_column('workspaces', sa.Column('pr_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'pr_number')
    op.drop_column('workspaces', 'fork_url')
    # ### end Alembic commands ###
